---
title: "analyze_growth"
author: "Catarina Pien"
date: '2022-09-16'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(readr)
library(here)
library(lme4)
library(car)
root <- "smelt_2019_allseasons"
```

# Condition Factor, Length, Weight
1. Read data

* a, e = wrap
* b, f = large. F = lots of dead smelt
* c, d = small

* We can keep c, d, b
```{r}
data <- read_csv(here(root,"data_clean","clean_smelt_cf_2019.csv")) %>%
  filter(!(grepl("FCCL", Cage) & Season == "Winter"),
         !(Cage %in% c("A", "E","F") & Season == "Winter")) %>%
  filter(!(Site == "RV" & is.na(Cage))) %>%
mutate(Season = factor(Season))

# Note there are a few fish in the summer that are cage-less. They may need to be identified as to which cage they should belong to??


str(data)
RV = filter(data, Site == "RV")
DWSC = filter(data, Site == "DWSC")
```

Weight pre-posts by season
```{r}
Summer <- data %>% filter(Season == "Summer")
Summer_wide <- Summer %>%
  pivot_wider(names_from = "Period",
              values_from = c("FL_cm", "Weight_g", "K"))
  
Fall <- data %>% filter(Season == "Fall")

Fall_wide <- Fall %>%
  pivot_wider(names_from = "Period",
              values_from = c("FL_cm", "Weight_g", "K"))
```

```{r}
hist(Summer$FL_cm_Pre)
hist(filter(Summer, Site=="RV")$FL_cm_Post)
hist(Summer$Weight_g_Pre)
hist(filter(Summer, Site=="RV")$Weight_g_Post)

hist(filter(data, Site == "RV")$FL_cm)
hist(filter(data, Site == "RV")$Weight_g)
hist(filter(data, Site == "RV")$K)

hist(filter(data, Site == "RV")$FL_cm)
hist(filter(data, Site == "RV")$Weight_g)
hist(filter(data, Site == "RV")$K)

hist(filter(data, Site == "DWSC")$FL_cm)
hist(filter(data, Site == "DWSC")$Weight_g)
hist(filter(data, Site == "DWSC")$K)

hist(Summer$FL_cm)
hist(Summer$Weight_g)
hist(sqrt(Summer$Weight_g))
hist(Summer$K)

hist(Fall$FL_cm)
hist(Fall$Weight_g)
hist(Fall$K)

shapiro.test(filter(data, Site == "DWSC")$FL_cm)
shapiro.test(filter(data, Site == "DWSC")$Weight_g)
shapiro.test(filter(data, Site == "DWSC")$K)

leveneTest(DWSC$FL_cm ~ DWSC$Period, data = data)
leveneTest(DWSC$Weight_g ~ DWSC$Period, data = data)
leveneTest(DWSC$K ~ DWSC$Period, data = data)


shapiro.test(Summer$FL_cm)
shapiro.test(sqrt(Summer$Weight_g))
shapiro.test(Summer$K)

leveneTest(Summer$FL_cm~Summer$Period)
leveneTest(Summer$Weight_g~Summer$Period)
leveneTest(Summer$K~Summer$Period)

shapiro.test(Fall$FL_cm)
shapiro.test(Fall$Weight_g)
shapiro.test(Fall$K)

leveneTest(Fall$FL_cm~Fall$Period)
leveneTest(Fall$Weight_g~Fall$Period)
leveneTest(Fall$K~Fall$Period)
```


## Summer
```{r}
t_sRV <- t.test(Summer$FL_cm_Pre, filter(Summer, Site=="RV")$FL_cm_Post) #no
t_sFC <- t.test(Summer$FL_cm_Pre, filter(Summer, Site=="FCCL")$FL_cm_Post) #yes



t.test(Summer$Weight_g_Pre, filter(Summer, Site=="RV")$Weight_g_Post) #on the border
t.test(Summer$Weight_g_Pre, filter(Summer, Site=="FCCL")$Weight_g_Post) #on the border

t.test(Summer$K_Pre, filter(Summer, Site=="RV")$K_Post) #yes
t.test(Summer$K_Pre, filter(Summer, Site=="FCCL")$K_Post) #yes




wilcox.test(Summer_wide$FL_cm_Pre, filter(Summer_wide, Site=="RV")$FL_cm_Post) #no
wilcox.test(Summer_wide$FL_cm_Pre, filter(Summer_wide, Site=="FCCL")$FL_cm_Post) #yes

wilcox.test(Summer_wide$Weight_g_Pre, filter(Summer_wide, Site=="RV")$Weight_g_Post) #no
wilcox.test(Summer_wide$Weight_g_Pre, filter(Summer_wide, Site=="FCCL")$Weight_g_Post) #no

wilcox.test(Summer_wide$K_Pre, filter(Summer_wide, Site=="RV")$K_Post) #yes
wilcox.test(Summer_wide$K_Pre, filter(Summer_wide, Site=="FCCL")$K_Post) #yes
```

```{r}
Summer$Period = factor(Summer$Period, levels = c("Pre", "Post"))
ggplot(Summer) + geom_boxplot(aes(Site, FL_cm, fill = Period)) 
ggplot(Summer) + geom_boxplot(aes(Site, K, fill = Period)) 

Fall$Period = factor(Fall$Period, levels = c("Pre", "Post"))
ggplot(Fall) + geom_boxplot(aes(Site, FL_cm, fill = Period))
ggplot(Fall) + geom_boxplot(aes(Site, Weight_g, fill = Period))
ggplot(Fall) + geom_boxplot(aes(Site, K, fill = Period)) 
```

# Fall
```{r}
wilcox.test(Fall_wide$FL_cm_Pre, filter(Fall_wide, Site=="RV")$FL_cm_Post) #no
wilcox.test(Fall_wide$FL_cm_Pre, filter(Fall_wide, Site=="Yolo")$FL_cm_Post) #yes
wilcox.test(Fall_wide$FL_cm_Pre, filter(Fall_wide, Site=="SM")$FL_cm_Post) #yes
wilcox.test(Fall_wide$FL_cm_Pre, filter(Fall_wide, Site=="FCCL")$FL_cm_Post) #yes

wilcox.test(Fall_wide$Weight_g_Pre, filter(Fall_wide, Site=="RV")$Weight_g_Post) #yes
wilcox.test(Fall_wide$Weight_g_Pre, filter(Fall_wide, Site=="Yolo")$Weight_g_Post) #yes
wilcox.test(Fall_wide$Weight_g_Pre, filter(Fall_wide, Site=="SM")$Weight_g_Post) #yes
wilcox.test(Fall_wide$Weight_g_Pre, filter(Fall_wide, Site=="FCCL")$Weight_g_Post) #yes

wilcox.test(Fall_wide$K_Pre, filter(Fall_wide, Site=="RV")$K_Post) #yes
wilcox.test(Fall_wide$K_Pre, filter(Fall_wide, Site=="Yolo")$K_Post) #yes
wilcox.test(Fall_wide$K_Pre, filter(Fall_wide, Site=="SM")$K_Post) #yes
wilcox.test(Fall_wide$K_Pre, filter(Fall_wide, Site=="FCCL")$K_Post) #yes
```

## Models
```{r}
RV_analysis <- data %>%
  group_by(Season, Site, Period, Cage) %>%
  summarize(meanK = mean(K, na.rm = TRUE),
            meanWt = mean(Weight_g, na.rm = TRUE)) %>%
  ungroup() %>%
  filter(!Site %in% c("SM", "Yolo", "DWSC"))

Post <- filter(RV_analysis, Period == "Post")%>%
  pivot_wider(names_from = "Period", values_from = "meanK")

# Use this to figure out means for batch pre for summer and fall
Pre <- filter(RV_analysis, Period == "Pre") %>%
  pivot_wider(names_from = "Period", values_from = c("meanK", "meanWt"))

# Now bring those values in here
RV_allfish <- data %>%
  filter(!Site %in% c("SM", "Yolo", "DWSC")) %>%
  pivot_wider(names_from = "Period",
              values_from = c("FL_cm", "Weight_g", "K")) %>%
  mutate(K_Pre = case_when(Season == "Fall"~ 0.7214667,
                         Season == "Summer" ~ 0.6626667,
                         Season == "Winter" ~ K_Pre),
         Weight_g_Pre = case_when(Season == "Fall" ~ 1.7213333,
                                Season == "Summer" ~ 0.8206667,
                                Season == "Winter" ~ Weight_g_Pre)) %>%
  mutate(deltaK = K_Post - K_Pre,
         deltaWt = Weight_g_Post - Weight_g_Pre) %>%
  filter(Site != "FCCL")

RV_sumfall <- filter(RV_allfish, Season != "Winter")
```

### Effect of Season at RV
```{r}
library(lmerTest)

# CF
m1 <- lmer(deltaK ~ Season + (1|Cage), data = RV_allfish)
summary(m1)
plot(m1)

m1b <- lmer(deltaK ~ Season + (1|Cage), data = RV_sumfall)
summary(m1b)
plot(m1b)

# Weight
m2 <- lmer(deltaWt~ Season + (1|Cage), data = RV_allfish)
summary(m2)
plot(m2)

m2b <- lmer(deltaWt ~ Season + (1|Cage), data = RV_sumfall)
summary(m2b)
plot(m2b) 

library(emmeans)
m1.emm <- emmeans(m1, "Season", data=RV_allfish)
pairs(m1.emm, adjust = "sidak")
plot(m1.emm, comparisons = TRUE) + theme_bw()

m2.emm <- emmeans(m2, "Season", data=RV_allfish)
pairs(m2.emm, adjust = "sidak")
plot(m2.emm, comparisons = TRUE) + theme_bw()
```

### Effect of Site in the Fall 
```{r}
Fallfish_avg <- data %>%
  group_by(Season, Site, Period, Cage) %>%
  summarize(meanK = mean(K, na.rm = TRUE),
            meanWt = mean(Weight_g, na.rm = TRUE)) %>%
  ungroup() %>%
  filter(Season == "Fall")

# Now bring those values in here
Fallfish <- data %>%
  filter(Season == "Fall") %>%
  pivot_wider(names_from = "Period",
              values_from = c("FL_cm", "Weight_g", "K")) %>%
  mutate(K_Pre = 0.7214667,
         Weight_g_Pre = 1.721333,
         deltaK = K_Post - K_Pre,
         deltaWt = Weight_g_Post - Weight_g_Pre) %>%
  filter(!is.na(K_Post))

```

### Effect of Site in the Fall
```{r}
library(lmerTest)

# CF ------
m3a <- lm(deltaK ~ Site, data = Fallfish)
summary(m3a)
plot(m3)


m3 <- lmer(deltaK ~ Site + (1|Cage), data = Fallfish, REML = TRUE)
summary(m3)
plot(m3)

# Not much difference in residual error by including cage effect. (0.09875 to 0.09787)




# Weight -----
m4a <- lm(deltaWt~ Site, data = Fallfish)
summary(m4a)
plot(m4a)

m4 <- lmer(deltaWt~ Site + (1|Cage), data = Fallfish)
summary(m4)
plot(m4)

# Not much difference in residual error by including cage effect. (0.471 to 0.466)

library(emmeans)
m3.emm <- emmeans(m3, "Site", data=Fallfish)
pairs(m3.emm, adjust = "sidak")
plot(m3.emm, comparisons = TRUE, type = "response") + theme_bw()

m4.emm <- emmeans(m4, "Site", data=Fallfish)
pairs(m4.emm, adjust = "sidak")
plot(m4.emm, comparisons = TRUE) + theme_bw()
```

```{r}
Fallfish <- Fallfish %>%
  mutate(res3 = resid(m3, type = "pearson"),
         res4 = resid(m4, type = "pearson"))
ggplot(Fallfish) + geom_histogram(aes(res3))
ggplot(Fallfish) + geom_boxplot(aes(Site, res3))

#hello


```

```{r}
m3
fixef(m3)
coef(summary(m3))
confint(m3, method = "Wald")
library(sjPlot)
plot_model(m3)
tab_model(m3,digits = 3)
```

```{r}
# set up to for loop through the cages
plot_cage = unique(Fallfish$Cage)
col_mat = matrix(data = c(140,81,10, 1,102,94, 118,42,131),
nrow = 3, ncol = 3, byrow = TRUE)
# create a vector that spans the observed range of temperatures for simulations
deltaK_seq = seq(min(Fallfish$deltaK), max(Fallfish$deltaK),
length.out=100)
# Use the effects package to calculate a 95% CI around the grand mean model
library(effects)
m3_eff=Effect(focal.predictors = "Site", mod=m3,
xlevels=list(deltaK=deltaK_seq))


# Use the random effect coefficients to generate random effect predictions
# across the observed range of temperatures
y_F1 = coef(m3)$Cage["B3",1] + coef(m3)$Cage["B3",2]*deltaK_seq
y_F2 = coef(m3)$Cage["B4",1] + coef(m3)$Cage["B4",2]*deltaK_seq
y_F3 = coef(m3)$Cage["B5",1] + coef(m3)$Cage["B5",2]*deltaK_seq

y_A = coef(m3)$Cage["A",1] + coef(m3)$Cage["A",2]*deltaK_seq
y_B = coef(m3)$Cage["B",1] + coef(m3)$Cage["B",2]*deltaK_seq
y_C = coef(m3)$Cage["C",1] + coef(m3)$Cage["C",2]*deltaK_seq

# plot it
par(mfrow=c(1,1), mar=c(4, 4.5, 1, 1)+0.1, oma=rep(0,4))
plot(Fallfish$deltaK ~ Fallfish$Site, type="n", 
     las=1,
ylab="deltaK", xlab = "Site")

for(i in 1:length(plot_cage)){
sub = subset(Fallfish, Fallfish$Cage == plot_cage[i])
points(sub$deltaK ~ sub$Site, pch=20,
col=rgb(col_mat[i,1],col_mat[i,2],col_mat[i,3],
maxColorValue = 255, alpha = 200))
}
lines(deltaK_seq, y_F1, type="l", lwd=1.5,
col=rgb(col_mat[1,1],col_mat[1,2],col_mat[1,3],
maxColorValue = 255, alpha = 225))

lines(deltaK_seq, y_F2, type="l", lwd=1.5,
col=rgb(col_mat[2,1],col_mat[2,2],col_mat[2,3],
maxColorValue = 255, alpha = 225))

lines(deltaK_seq, y_F3, type="l", lwd=1.5,
col=rgb(col_mat[3,1],col_mat[3,2],col_mat[3,3],
maxColorValue = 255, alpha = 225))

lines(deltaK_seq, y_A, type="l", lwd=1.5,
col=rgb(col_mat[3,1],col_mat[3,2],col_mat[3,3],
maxColorValue = 255, alpha = 225))

lines(deltaK_seq, y_B, type="l", lwd=1.5,
col=rgb(col_mat[3,1],col_mat[3,2],col_mat[3,3],
maxColorValue = 255, alpha = 225))

lines(deltaK_seq, y_C, type="l", lwd=1.5,
col=rgb(col_mat[3,1],col_mat[3,2],col_mat[3,3],
maxColorValue = 255, alpha = 225))

polygon(x = c(deltaK_seq, deltaK_seq[100], rev(deltaK_seq), deltaK_seq[1]),
y=c(m3_eff$lower, m3_eff$upper[100],
rev(m3_eff$upper), m3_eff$lower[1]),
col=gray(0.25,0.25),
border=NA)
lines(m3_eff$fit~deltaK_seq, lwd=3.5, col="black")
box(which="outer")
```

