---
title: "Delta Smelt Enclosure Study 2019 Hybrid Paper Diet Analysis"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

# load packages
```{r message=FALSE, warning=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidyverse)
library(FSA)
library(lubridate)
```

# bring in contractor (UW) data
```{r}
diet2 <- read_csv("smelt_2019_allseasons/data_raw/DSM Cage Diets 2019-2020.csv") #new data, not edited at all

diet2$Date <- mdy(diet2$Date)

#format 
#rename columns
diet2 <- diet2 %>% rename(Cage.ID = "Cage ID", Contents.Weight = "Total Contents Weight", Prey.Taxa = "Prey Taxa", LH.Stage = "LH Stage")

#add taxa column (choose taxa based on what is present in the dataframe)
diet2$Taxa <- as.character(NA) 

str(diet2)

diet2[diet2$Prey.Taxa %in% c("Bosmina sp.", "Chydorus sp.", "Daphnia sp.", "Ceriodaphnia sp.", "Chydoridae", "Crangonyx sp.", "Scapholeberis sp.", "Simocephalus sp.", "Eurycercus sp.", "Leydigia sp.", "Cladocera", "Sida sp.", "Alona sp.", "Diaphanosoma sp."),]$Taxa <- "Cladocera"

diet2[diet2$Prey.Taxa %in% c("Americorophium sp.", "Americorophium spinicorne", "Eogammarus confervicolus", "Gammaridea", "Hyallela azteca", "Crangonyx sp.", "Corophiidae", "Amphipoda"),]$Taxa <- "Amphipod"

diet2[diet2$Prey.Taxa %in% c("Pseudodiaptomus forbesi", "Calanoida", "Eurytemora affinis", "Diaptomidae", "Sinocalanus doerrii", "Osphranticum labronectum"),]$Taxa <- "Calanoid"

diet2[diet2$Prey.Taxa %in% c("Acanthocyclops sp.", "Macrocyclops sp.", "Diacyclops thomasi", "Eucyclops sp.", "Cyclopoida", "Halicyclops sp.", "Mesocyclops sp.", "Tropocyclops sp.", "Tropocyclops sp."),]$Taxa <- "Cyclopoid"

diet2[diet2$Prey.Taxa %in% c("Chironomidae", "Diptera"),]$Taxa <- "Diptera"

diet2[diet2$Prey.Taxa %in% c("empty", "EMPTY"),]$Taxa <- "empty"

diet2[diet2$Prey.Taxa %in% c("Harpacticoida"),]$Taxa <- "Harpacticoid"

diet2[diet2$Prey.Taxa %in% c("Ostracoda"),]$Taxa <- "Ostracod"

diet2[diet2$Prey.Taxa %in% c("Fish", "Acari", "Insecta", "Bivalvia", "Culicidae", "egg unidentified", "Corixidae", "Hemiptera", "plant seed", "plant matter", "Unidentified", "Mysidacea", "Cumacea"),]$Taxa <- "Other"

new_DF <- diet2[is.na(diet2$Taxa),] #update code above with new prey.taxa that weren't found in previous diets
#there are two "copepoda" entries with no count or location...don't seem that important so I am going to just go ahead and remove them
diet2[diet2$Taxa %in% c("empty"),]$Count <- "0"
diet2 <- diet2[!is.na(diet2$Count),]

#Tag column currently has rows with just the Tag and others with location, date, and tag
#first break those two kinds of columns apart
weird.tag <- diet2[is.na(diet2$Location),]
norm.tag <- diet2[!is.na(diet2$Location),]

#then for break out the Tag ID into Location and tag (remove date)
weird.tag <- weird.tag %>% separate(Tag, c("Location", "X.date", "Tag"))

#remove new date column
weird.tag <- subset(weird.tag, select = -6)

#add mesh types for prototype experiment
#create new column for mesh types
Cage_type <- as.data.frame(matrix(0, ncol = 2, nrow = 6))
colnames(Cage_type) <- c("Cage.ID", "Mesh")

Cage_type$Cage.ID <- c("A", "B", "C", "D", "E", "F")
Cage_type$Mesh <- c("small", "large", "wrap", "wrap", "small", "large")

norm.tag2 <- merge(norm.tag, Cage_type, by = "Cage.ID", all.x = TRUE)

#add mesh types (NA) for summer/fall experiements
weird.tag$Mesh <- NA 

#merge the two
diet <- rbind(weird.tag, norm.tag2)

#change location titles 
diet$Location[diet$Location =="RIVERS"] <- "RV.Winter"
diet$Location[diet$Location =="Sac DWSC"] <- "DWSC.Winter"
diet$Location[diet$Location =="SM"] <- "SM.Fall"
diet$Location[diet$Location =="YB"] <- "YB.Fall"
#RV a little trickier with two dates
diet$ld = paste(diet$Location, diet$Date)
diet$Location[diet$ld =="RV 2019-08-28"] <- "RV.Summer"
diet$Location[diet$ld =="RV 2019-11-06"] <- "RV.Fall"
RV <- filter(diet, Location == "RV")
diet$Location[diet$ld =="RV 2019-11-07"] <- "RV.Fall"

diet <- subset(diet, select = -16)
```

# prep merged data for taxa proportion
```{r}
#remove FCCL controls
diet<-diet[diet$Cage.ID != "FCCL Control Tank 1",]
diet<-diet[diet$Cage.ID != "FCCL Control Tank 2",]
diet<-diet[diet$Cage.ID != "FCCL Control",]

#fix fish that were assigned the wrong cage (came up during summary stats, check against dissected fish data, likely E and F were misread)
diet[diet$Tag=='RK10', 'Cage.ID'] <- "E"
diet[diet$Tag=='RN93', 'Cage.ID'] <- "E"

#change count to numeric
diet$Count<-as.numeric(diet$Count)

#output says NAs introduced by coercion - check NA's
newDF <- diet[is.na(diet$Count),]

#one NA next to a gammaridae - comment says that it was too digested and could be more than one individual, to be safe just going to add a count of "1" for this observation; found it on row 413
diet<-diet %>% replace_na(list(Count=1))

#change count to numeric
diet$Count<-as.numeric(diet$Count)

diet$tlc = paste(diet$Tag, diet$Location, diet$Cage.ID)

#sum for taxa abundance among individual fish
taxa_tag<- diet %>% 
  group_by(Location, tlc, Taxa) %>% 
  summarize("count.sum"= sum(Count))

#sum taxa across stomach
stomach<- diet %>% 
  group_by(Location, tlc) %>% 
  summarize("stomach.sum"= sum(Count))

stomach_abundance<-merge(taxa_tag, stomach, by = "tlc")

stomach_abundance$proportion<-(stomach_abundance$count.sum/stomach_abundance$stomach.sum)*100

#add rows for all taxa for all fish so every taxa shows up for every stomach
full.prop<-stomach_abundance %>% complete(tlc, Taxa) %>%
  as.data.frame()

full.prop.2<-merge(full.prop, stomach, by = "tlc")

#select columns I want for proportion
full.prop.3<-subset(full.prop.2, select=c("Location", "tlc", "Taxa", "proportion"))

#replace proportion Nas with zeros
diet.prop<-full.prop.3 %>% replace_na(list(proportion=0))

#average across fish
diet.prop.mean<- diet.prop %>% 
  group_by(Taxa, Location) %>% 
  summarize("prop.mean"= mean(proportion))
```

# plot number of empty stomachs
## these will not be included in the 100% stacked bar later
```{r}
#order locations
stomach_abundance$Location <- stomach_abundance$Location.x
stomach_abundance$Location <- ordered(stomach_abundance$Location, levels = c("DWSC.Winter", "RV.Winter", "RV.Summer", "SM.Fall", "YB.Fall", "RV.Fall"))

#subset for only empty stomachs
empty <- filter(stomach_abundance, Taxa == "empty")
 
ggplot(empty, aes(Location)) + geom_bar() + scale_x_discrete(drop=FALSE)
```

# plot mean proportion in 100% stacked bar
```{r}
#remove empty
prop<-diet.prop.mean[diet.prop.mean$Taxa != "empty",]

#order locations
prop$Location <- ordered(prop$Location, levels = c("DWSC.Winter", "RV.Winter", "RV.Summer", "RV.Fall", "YB.Fall", "SM.Fall"))

#order taxa to match zoop plot
prop$Taxa <- factor(prop$Taxa, levels=c("Calanoid", "Cladocera", "Cyclopoid", "Harpacticoid", "Ostracod", "Other", "Amphipod", "Diptera"))

ggplot(data=prop, aes(x=Location, y =prop.mean, fill=Taxa)) +
    geom_bar(position="fill", stat="identity", colour="black") +
  theme_bw() +
  viridis::scale_fill_viridis(discrete = TRUE, option = "plasma") +
  theme(legend.position="right", axis.title.x = element_blank())+
  labs(y = "Mean Contribution to Diet")

ggsave("smelt_2019_allseasons/figures/diet19_onepanel.png", dpi=250, height=4.5, width=7, units="in")

#facet by season

#create season column
prop2 <- prop
prop2$Season <- "NA"
prop2[prop2$Location %in% c("DWSC.Winter", "RV.Winter"),]$Season <- "Winter"
prop2[prop2$Location %in% c("RV.Summer"),]$Season <- "Summer"
prop2[prop2$Location %in% c("RV.Fall", "YB.Fall", "SM.Fall"),]$Season <- "Fall"

#change Location to drop season
prop2$Location <- as.character(prop2$Location)
prop2$Location[prop$Location =="DWSC.Winter"] <- "DWSC"
prop2[prop2$Location %in% c("RV.Winter", "RV.Summer", "RV.Fall"),]$Location <- "RV"
prop2$Location[prop$Location =="YB.Fall"] <- "YB"
prop2$Location[prop$Location =="SM.Fall"] <- "SM"

#order seasons
prop2$Season <- factor(prop2$Season, levels=c("Winter", "Summer", "Fall"))

#order locations
prop2$Location <- factor(prop2$Location, levels=c("DWSC", "RV", "YB", "SM"))

#order taxa to match zoop plot
prop2$Taxa <- factor(prop2$Taxa, levels=c("Calanoid", "Cladocera", "Cyclopoid", "Harpacticoid", "Ostracod", "Other", "Amphipod", "Diptera"))

#plot
ggplot(data=prop2, aes(x=Location, y =prop.mean, fill=Taxa)) +
  geom_bar(position="fill", stat="identity", colour="black", width=0.75) +
  facet_wrap(~Season, ncol=1) +
  theme_bw() +
  viridis::scale_fill_viridis(discrete = TRUE, option = "plasma") +
  theme(legend.position="right", axis.title.x = element_blank())+
  labs(y = "Mean Contribution to Diet") +
   theme(legend.position="right")+
      theme(axis.text = element_text(size = 12),
      axis.title = element_text(size = 12),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 10))

ggsave("smelt_2019_allseasons/figures/diet19_multipanel.png", dpi=250, height=6, width=6, units="in")

library(scales)
show_col(viridis_pal(option = "plasma")(8))
viridis_pal(option = "plasma")(8)
```