---
title: "plot_weight_length_cf"
author: "Catarina Pien"
date: "12/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(here)
```

```{r}
smeltdata <- read_csv(here("smelt_2019_allseasons", "data_clean", "clean_smelt_cf_2019.csv"), col_types = cols(.default="f", FL_cm = "d", Weight_g = "d", K = "d", ID = "c"))
glimpse(smeltdata)
```

```{r}
smeltdata2 <- smeltdata %>%
  filter(!is.na(K)) 
```

Summarize data
```{r}
level_key = c(Pre = "Pre-Deployment", Post = "Post-Deployment")
level_key = c(`Pre-Deployment` = "Pre", `Post-Deployment` = "Post")
summarydata <- smeltdata2 %>%
  group_by(Deployment, Site, Period) %>%
  summarize(meanCF = mean(K, na.rm = TRUE),
            sdCF = sd(K, na.rm = TRUE),
            meanFL = mean(FL_cm, na.rm = TRUE),
            sdFL = sd(FL_cm, na.rm = TRUE),
            meanWeight = mean(Weight_g, na.rm = TRUE),
            sdWeight = sd(Weight_g, na.rm = TRUE),
            n = n())%>%
  ungroup() %>%
  mutate(Period = recode(Period,"Pre" = "Pre-Deployment", "Post" = "Post-Deployment"))
```

Plot K
```{r}
box_K <- ggplot(smeltdata2, aes(x = Period, y = K, fill = Site)) + 
  geom_boxplot() + 
  facet_wrap(Deployment~.) + 
  viridis::scale_fill_viridis(discrete = TRUE, option = "plasma") +
  labs(y = "Condition Factor (K)") + 
  theme_bw()+
  theme(axis.title.x = element_blank(),
        axis.text = element_text(size = 11),
        strip.text = element_text(size = 11),
        legend.text = element_text(size = 11),
        legend.title = element_text(size = 11.5))
```

Plot Length
```{r}
box_FL <- ggplot(smeltdata2, aes(x = Period, y = FL_cm, fill = Site)) + 
  geom_boxplot() + 
  facet_wrap(Deployment~.) + 
  viridis::scale_fill_viridis(discrete = TRUE, option = "plasma") +
  labs(y = "Fork Length (cm)") +
  theme_bw()+
  theme(axis.title.x = element_blank(),
        axis.text = element_text(size = 11),
        strip.text = element_text(size = 11))
```

Plot Weight
```{r}
box_Wt <- ggplot(smeltdata2, aes(x = Period, y = Weight_g, fill = Site)) + 
  geom_boxplot() + 
  facet_wrap(Deployment~.) + 
  viridis::scale_fill_viridis(discrete = TRUE, option = "plasma") +
  labs(y = "Weight (g)") + 
  theme_bw()+
  theme(axis.title.x = element_blank(),
        axis.text = element_text(size = 11),
        strip.text = element_text(size = 11))
```

```{r}
library(ggpubr)
figure_comb <- ggarrange(box_FL, box_Wt, box_K, nrow = 3, common.legend = TRUE)


tiff(filename = file.path("smelt_2019_allseasons/figures/FL-Wt-K.tiff"), res = 300, width = 7, height = 7, units = "in", pointsize = 10, type = "cairo", compression = "lzw")
annotate_figure(figure_comb, bottom = text_grob("Deployment Period", size = 11) )
dev.off()

```

