---
librarytitle: "Zoop Plotting"
output: html_document
editor_options: 
  chunk_output_type: console
---
# load packages
```{r}
library(tidyverse)
library(lubridate)
library(Polychrome)
```

# load & prep summer/fall data
```{r}
zoop <- read_csv("smelt_2019_allseasons/data_raw/ZoopData_SummerFall_2019.csv")

zoop$Date <- mdy(zoop$Date)
zoop$Day <- day(zoop$Date)
zoop$Month <- month(zoop$Date)
zoop$Month <- month.abb[zoop$Month]
zoop$MD <- paste(zoop$Month, zoop$Day, sep="-")

#add ring size (0.5m for 50um net)
zoop$RingSize_m <- 0.5

#add 0s for count with NA
zoop$Count[is.na(zoop$Count)] <- 0

#bring in tow data
aug <- read_csv("smelt_2019_allseasons/data_raw/Field_Environmental_Data_Aug_qaqc'ed_11.04.20.csv")
oct <- read_csv("smelt_2019_allseasons/data_raw/Field_Environmental_Data_Oct_qaqc'ed_12.11.20.csv")
aug$Date <- mdy(aug$Date)
oct$Date <- mdy(oct$Date)

#condense to columns of interest
aug2 <- aug[c(1,4,22,24:27)]
oct2 <- oct[c(1,4,26,28:31)]

tow <- rbind(aug2,oct2)
tow2 <- tow[!is.na(tow$Location),]

#merge
#rename column
zoop <- zoop %>% rename(Location = "Station")

#make locations match
unique(zoop$Location)
unique(tow2$Location)

zoop[zoop$Location %in% c("STTD", "STTD-YOLO", "YOLO"),]$Location <- "YB"
tow2[tow2$Location %in% c("Yolo"),]$Location <- "YB"

all <- merge(zoop, tow2, by = c('Location', 'Date'))

#calculate abundance -----------------------
all$distance <- (all$Revs)*57560/999999 #57,560 = low speed rotor constant
all$volumesampled <- ((pi*(all$RingSize_m^2))/4)*all$distance
all$samplecount <- (all$TotalVolume_ml/all$Subsampled_ml)*all$Count

#calculate ind/m3
all$ind_m3 <- all$samplecount/all$volumesampled

#remove 0's
caught <- all[!(all$ind_m3==0),]

#add taxa

caught[caught$ID %in% c("Rotifers", "Copepod nauplii"),]$Taxa <- "Microzoo"

caught[caught$ID %in% c("Ostracods"),]$Taxa <- "Ostracod"

caught[caught$ID %in% c("Bosmina", "Ceriodaphnia", "Diaphanosoma", "Alona", "Chydorus", "Eurycercus", "Monospilus", "Alonella", "Daphnia", "Ilyocryptus", "Camptocercus", "Simocephalus", "Pleuroxus", "Graptoleberis", "Macrothrix"),]$Taxa <- "Cladocera"

caught[caught$ID %in% c("Cyclopoid copepodid", "Tropocyclops prasinus", "Limnoithona tetraspina", "Diacyclops thomasi", "Eucyclops sp.", "Mesocyclops edax", "Microcyclops rubellus", "Tropocylcops prasinus", "Acanthocyclops vernalis adult", "Eucyclops pectinifer", "Paracyclops spp."),]$Taxa <- "Cyclopoid"

caught[caught$ID %in% c("Calanoid copepodid", "Pseudodiaptomus forbesi adult", "Pseudodiaptomus forbesi copepodid", "Eurytemora affinis adult", "Sinocalanus doerrii adult"),]$Taxa <- "Calanoid"

caught[caught$ID %in% c("Harpacticoids"),]$Taxa <- "Harpacticoid"

caught[caught$ID %in% c("Maeotias marginata (large)"),]$Taxa <- "Other"
```

# plot summer/fall data
```{r}
#order factors
unique(caught$MD)
caught$MD <- factor(caught$MD, levels=c("Jul-31", "Aug-1", "Aug-2",  "Aug-5", "Aug-6", "Aug-8",  "Aug-12", "Aug-15", "Aug-19", "Aug-22", "Aug-26", "Oct-10", "Oct-11", "Oct-15", "Oct-16", "Oct-18", "Oct-21", "Oct-25", "Oct-28", "Nov-4"))

legend_title <- "Species"

pal36 <- palette36.colors(36)
pal36 <- as.vector(t(pal36))

ggplot() +
  geom_bar(position = "fill", stat = "identity", data=caught, aes (x=MD, y=samplecount, fill=ID), colour="black", width = .5) +
  facet_wrap(~Location, ncol = 1) +
  theme_bw() + 
  scale_fill_manual(values=pal36)+
  labs(x = "Date") +
  labs(y = "Relative Abundance of all Zoop in Sample")+
  theme(legend.position="right")+
      theme(axis.text = element_text(size = 12),
      axis.title = element_text(size = 12),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 10),
      axis.text.x = element_text(angle = 90))

#plot with microzoop removed
macro <- caught[!(caught$ID=="Copepod nauplii"),]
macro <- macro[!(macro$ID=="Rotifers"),]

ggplot() +
  geom_bar(position = "fill", stat = "identity", data=macro, aes (x=MD, y=samplecount, fill=ID), colour="black", width = .5) +
  facet_wrap(~Location, ncol = 1) +
  theme_bw() + 
  scale_fill_manual(values=pal36)+
  labs(x = "Date") +
  labs(y = "Relative Abundance of Macrozoop in Sample")+
  theme(legend.position="right")+
      theme(axis.text = element_text(size = 12),
      axis.title = element_text(size = 12),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 10),
      axis.text.x = element_text(angle = 90))
```

#bring in winter data
```{r}
#prep of this dataset (code and raw data) can be found on GitHub under Smelt Cages > smelt_2019_winterspring

winter <- read_csv("smelt_2019_allseasons/data_clean/zoop_abundance.csv")

winter$Day <- day(winter$Date)
winter$Month <- month(winter$Date)
winter$Month <- month.abb[winter$Month]
winter$MD <- paste(winter$Month, winter$Day, sep="-")

#remove throw samples
winter <- winter[!(winter$Method=="Throw"),]

#merge with catch df
#condense to columns of interest
winter2 <- winter[c(1,2,13,27,30,22,23)]
caught2 <- caught[c(1,2,7,10,20,29,30)]

#rename column
winter2 <- winter2 %>% rename(ID = "Taxon")

#change ostracod taxa
winter2[winter2$ID %in% c("Ostracods"),]$Taxa <- "Ostracod"

#make locations match
unique(winter2$Location)
unique(caught2$Location)

all2019 <- rbind(winter2, caught2)

#remove 0's
caught.19 <- all2019[!(all2019$ind_m3==0),]
```

# plot all 2019
```{r}
#create season column
caught.19$Season <- as.character(NA)

caught.19[caught.19$MD %in% c("Jan-24", "Jan-29", "Jan-31", "Feb-6", "Feb-8", "Feb-12", "Feb-15", "Feb-22", "Feb-28", "Mar-1", "Mar-4", "Mar-8", "Mar-13", "Mar-19", "Mar-25"),]$Season <- "Winter"

caught.19[caught.19$MD %in% c("Jul-31", "Aug-1", "Aug-2",  "Aug-5", "Aug-6", "Aug-8",  "Aug-12", "Aug-15", "Aug-19", "Aug-22", "Aug-26"),]$Season <- "Summer"

caught.19[caught.19$MD %in% c("Oct-10", "Oct-11", "Oct-15", "Oct-16", "Oct-18", "Oct-21", "Oct-25", "Oct-28", "Nov-4"),]$Season <- "Fall"

caught.sea <- caught.19 %>% 
  group_by(Season, Location, Taxa) %>% 
  summarize("sum.count"= sum(samplecount))

#order seasons
caught.sea$Season <- factor(caught.sea$Season, levels=c("Winter", "Summer", "Fall"))

#order locations
caught.sea$Location <- factor(caught.sea$Location, levels=c("DWSC", "RV", "YB", "SM"))

ggplot() +
  geom_bar(position = "fill", stat = "identity", data=caught.sea, aes (x=Location, y=sum.count, fill=Taxa), colour="black", width = .75) +
  facet_wrap(~Season, ncol = 1) +
  theme_bw() + 
  viridis::scale_fill_viridis(discrete = TRUE, option = "plasma") +
  labs(x = "Location") +
  labs(y = "Relative Abundance")+
  theme(legend.position="right")+
      theme(axis.text = element_text(size = 12),
      axis.title = element_text(size = 12),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 10))

ggsave("smelt_2019_allseasons/figures/allzoop19.png", dpi=250, height=6, width=6, units="in")

#plot with microzoop removed
caught.sea2 <- caught.sea[!(caught.sea$Taxa=="Microzoo"),]

#create custom palette from viridis to match taxa from diet plot
zoopPalette <- c("#0D0887FF", "#5402A3FF", "#8B0AA5FF", "#B93289FF", "#DB5C68FF", "#F48849FF")

ggplot() +
  geom_bar(position = "fill", stat = "identity", data=caught.sea2, aes (x=Location, y=sum.count, fill=Taxa), colour="black", width = .75) +
  facet_wrap(~Season, ncol = 1) +
  theme_bw() + 
  scale_fill_manual(values=zoopPalette)+
  labs(x = "Location") +
  labs(y = "Relative Abundance")+
  theme(legend.position="right")+
      theme(axis.text = element_text(size = 12),
      axis.title = element_text(size = 12),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 10))

ggsave("smelt_2019_allseasons/figures/macrozoop19.png", dpi=250, height=6, width=6, units="in")
```

# repeated measures ANOVA
```{r}
#combine taxa 
for.mod<-caught.19 %>% 
  group_by(Location, Date, Taxa, Season) %>% 
  summarize("ind.all"=sum(ind_m3))

shapiro.test(for.mod$ind.all) #very significant, no ANOVA
```
